logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/MatadorProBr/revanced-extended-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
patches-version = "v2.228.0-dev.12"
integrations-version = "v0.155.0-dev.7"
rv-brand = "RVX anddea"
arch = "arm64-v8a"
build-mode = "module"
module-prop-name = "YT-RVX"
included-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Force player buttons background' 'Hide animated button background' 'Hide double tap to like animations' 'Force hide player buttons background' 'Hide player button background' 'Hide voice search button'"
excluded-patches = "'Append time stamps information' 'Custom branding heading' 'Custom double tap length' 'Custom package name' 'Enable wide search bar' 'Keep landscape mode' 'Layout switch' 'Translations' 'Disable HDR auto brightness' 'Change player flyout panel toggles'"
#version = "19.05.36"

[YT Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "RVX-Music anddea"
arch = "arm64-v8a"
build-mode = "module"
module-prop-name = "YTM-RVX"
included-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Hide voice search button'"
excluded-patches = "'Certificate spoof' 'Custom package name' 'Custom playback speed' 'Translations' 'Enable old player layout' 'Enable old player background' 'Enable old style miniplayer' 'Enable color match player' 'Enable zen mode'"
